- name: Start kubernetes cluster
  shell: ./opt/kubernetes/cluster/kube-up.sh
  environment:
    KUBERNETES_PROVIDER: ubuntu 
  sudo: yes

- name: Setup DNS
  shell: ./opt/kubernetes/cluster/ubuntu/deployAddons.sh
  environment:
    KUBERNETES_PROVIDER: ubuntu 
  sudo: yes
